/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:00c55712-7421-4844-b8b3-84260650dc72",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1owt4G89y",
    "aws_user_pools_web_client_id": "52tjn53ksia09mve7j0sdoa4kl",
    "oauth": {}
};


export default awsmobile;
